In [2]:
weight = [0.1, 0.2, 0]

def neural_network(input,weight):
    pred = w_sum(input, weight)
    return pred

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output+=(a[i]*b[i])
    return output


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[2],wlrec[2],nfans[2]]
pred = neural_network(input,weight)
print(pred)

1.1500000000000001


In [4]:
import numpy as np
weights = np.array([0.1, 0.2, 0])
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(pred)

0.9800000000000001


In [5]:
arr = np.array([[1,0],[0,1],[1,1]])
arr1 = np.array([[1,2,1],[0,1,2]])
print(arr.dot(arr1))
print(arr[0]-arr[1])
error = (1/len(input))*np.sum(np.square(input-weights))
print (error)

[[1 2 1]
 [0 1 2]
 [1 3 3]]
[ 1 -1]
24.0675


In [6]:
ih_wgt = np.array([
            [0.1, 0.2, -0.1],
            [-0.1,0.1, 0.9],
            [0.1, 0.4, 0.1]]).T
hp_wgt = np.array([
            [0.3, 1.1, -0.3],
            [0.1, 0.2, 0.0],
            [0.0, 1.3, 0.1]]).T
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


In [7]:
knob_weight = 0.5
input = 0.5
goal_pred = 0.8

pred = input * knob_weight
error = (pred - goal_pred) ** 2
print(error)

0.30250000000000005


In [8]:
weight = 0.5
input = 0.5
goal_prediction = 0.8

step_amount = 0.0001

for iteration in range(11010):
    prediction = input * weight
    error = (prediction - goal_prediction) ** 2

    

    up_prediction = input * (weight + step_amount)
    up_error = (goal_prediction - up_prediction) ** 2

    down_prediction = input * (weight - step_amount)
    down_error = (goal_prediction - down_prediction) ** 2

    if(down_error<up_error):
        weight = weight - step_amount
    if(down_error>up_error):
        weight = weight + step_amount
print("Ошибка: "+str(error)+"    Предсказание: "+str(prediction))

Ошибка: 2.499999993937632e-09    Предсказание: 0.8000499999999394


In [7]:
weight =0.5
goal_pred =0.8
input =0.5
for iteration in range(100): 
    pred = input * weight
    error = (pred - goal_pred) ** 2
    direction_and_amount = (pred - goal_pred) * input
    weight = weight - direction_and_amount
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.30250000000000005 Prediction:0.25
Error:0.17015625000000004 Prediction:0.3875
Error:0.095712890625 Prediction:0.49062500000000003
Error:0.05383850097656251 Prediction:0.56796875
Error:0.03028415679931642 Prediction:0.6259765625
Error:0.0170348381996155 Prediction:0.669482421875
Error:0.00958209648728372 Prediction:0.70211181640625
Error:0.005389929274097089 Prediction:0.7265838623046875
Error:0.0030318352166796153 Prediction:0.7449378967285156
Error:0.0017054073093822882 Prediction:0.7587034225463867
Error:0.0009592916115275371 Prediction:0.76902756690979
Error:0.0005396015314842384 Prediction:0.7767706751823426
Error:0.000303525861459885 Prediction:0.7825780063867569
Error:0.00017073329707118678 Prediction:0.7869335047900676
Error:9.603747960254256e-05 Prediction:0.7902001285925507
Error:5.402108227642978e-05 Prediction:0.7926500964444131
Error:3.038685878049206e-05 Prediction:0.7944875723333098
Error:1.7092608064027242e-05 Prediction:0.7958656792499823
Error:9.614592036015323

In [8]:
weight, goal_pred, input = (0.0, 0.8, 0.5)
for iteration in range(900):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * input
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.6400000000000001 Prediction:0.0
Error:0.3600000000000001 Prediction:0.2
Error:0.2025 Prediction:0.35000000000000003
Error:0.11390625000000001 Prediction:0.4625
Error:0.06407226562500003 Prediction:0.546875
Error:0.036040649414062535 Prediction:0.61015625
Error:0.020272865295410177 Prediction:0.6576171875
Error:0.011403486728668217 Prediction:0.693212890625
Error:0.006414461284875877 Prediction:0.71990966796875
Error:0.0036081344727426873 Prediction:0.7399322509765625
Error:0.0020295756409177616 Prediction:0.7549491882324219
Error:0.001141636298016239 Prediction:0.7662118911743164
Error:0.0006421704176341359 Prediction:0.7746589183807373
Error:0.00036122085991920354 Prediction:0.7809941887855529
Error:0.000203186733704552 Prediction:0.7857456415891647
Error:0.0001142925377088099 Prediction:0.7893092311918736
Error:6.428955246120602e-05 Prediction:0.7919819233939052
Error:3.616287325942905e-05 Prediction:0.7939864425454288
Error:2.034161620842884e-05 Prediction:0.7954898319090716

Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380

Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380657631324e-32 Prediction:0.7999999999999998
Error:4.930380

In [9]:
weight, goal_pred, input = (0.0, 0.8, 1.1)
for iteration in range(10):
    print("---------\nWeight:" + str(weight))
    pred = input * weight
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weight_delta = delta * input
    weight = weight - weight_delta
    print("Error:" + str(error) + " Prediction:" + str(pred))
    print("Delta:" + str(delta) + " Weight Delta:" + str(weight_delta))

---------
Weight:0.0
Error:0.6400000000000001 Prediction:0.0
Delta:-0.8 Weight Delta:-0.8800000000000001
---------
Weight:0.8800000000000001
Error:0.02822400000000005 Prediction:0.9680000000000002
Delta:0.16800000000000015 Weight Delta:0.1848000000000002
---------
Weight:0.6951999999999999
Error:0.0012446784000000064 Prediction:0.76472
Delta:-0.03528000000000009 Weight Delta:-0.0388080000000001
---------
Weight:0.734008
Error:5.4890317439999896e-05 Prediction:0.8074088
Delta:0.007408799999999993 Weight Delta:0.008149679999999992
---------
Weight:0.72585832
Error:2.4206629991042546e-06 Prediction:0.798444152
Delta:-0.0015558480000000818 Weight Delta:-0.0017114328000000902
---------
Weight:0.7275697528
Error:1.0675123826048965e-07 Prediction:0.80032672808
Delta:0.00032672808000000497 Weight Delta:0.0003594008880000055
---------
Weight:0.727210351912
Error:4.707729607278605e-09 Prediction:0.7999313871032001
Delta:-6.861289679993554e-05 Weight Delta:-7.54741864799291e-05
---------
Weight:0

In [10]:
weight = [3.9999999, 1.142999, 3.999999]
input = [0.2, 0.7, 0.2]
goal_prediction = 0.8

step_amount = 0.001

for iteration in range(100):
    for i in range(len(weight)):
        error = ((input[i] * weight[i]) - goal_prediction) ** 2

        print("["+str(i)+"]Ошибка: "+str(error)+"    Предсказание: "+str(input[i] * weight[i]))

        up_prediction = input[i] * (weight[i] + step_amount)
        up_error = (goal_prediction - up_prediction) ** 2

        down_prediction = input[i] * (weight[i] - step_amount)
        down_error = (goal_prediction - down_prediction) ** 2

        if(down_error<up_error):
            weight[i] = weight[i] - step_amount
        if(down_error>up_error):
            weight[i] = weight[i] + step_amount
    print("\n\n")
print(weight)

[0]Ошибка: 3.999999995789153e-16    Предсказание: 0.79999998
[1]Ошибка: 9.86049000000484e-09    Предсказание: 0.8000993000000001
[2]Ошибка: 4.000000000230045e-14    Предсказание: 0.7999998



[0]Ошибка: 3.99920003999954e-08    Предсказание: 0.80019998
[1]Ошибка: 3.608404899998781e-07    Предсказание: 0.7993993000000001
[2]Ошибка: 3.992004000003326e-08    Предсказание: 0.8001998000000001



[0]Ошибка: 3.999999995789153e-16    Предсказание: 0.79999998
[1]Ошибка: 9.86049000000484e-09    Предсказание: 0.8000993000000001
[2]Ошибка: 3.999999995789153e-14    Предсказание: 0.7999998000000001



[0]Ошибка: 3.99920003999954e-08    Предсказание: 0.80019998
[1]Ошибка: 3.608404899998781e-07    Предсказание: 0.7993993000000001
[2]Ошибка: 3.992004000003326e-08    Предсказание: 0.8001998000000001



[0]Ошибка: 3.999999995789153e-16    Предсказание: 0.79999998
[1]Ошибка: 9.86049000000484e-09    Предсказание: 0.8000993000000001
[2]Ошибка: 3.999999995789153e-14    Предсказание: 0.7999998000000001



[0]О

[2]Ошибка: 3.999999995789153e-14    Предсказание: 0.7999998000000001



[0]Ошибка: 3.99920003999954e-08    Предсказание: 0.80019998
[1]Ошибка: 3.608404899998781e-07    Предсказание: 0.7993993000000001
[2]Ошибка: 3.992004000003326e-08    Предсказание: 0.8001998000000001



[0]Ошибка: 3.999999995789153e-16    Предсказание: 0.79999998
[1]Ошибка: 9.86049000000484e-09    Предсказание: 0.8000993000000001
[2]Ошибка: 3.999999995789153e-14    Предсказание: 0.7999998000000001



[0]Ошибка: 3.99920003999954e-08    Предсказание: 0.80019998
[1]Ошибка: 3.608404899998781e-07    Предсказание: 0.7993993000000001
[2]Ошибка: 3.992004000003326e-08    Предсказание: 0.8001998000000001



[0]Ошибка: 3.999999995789153e-16    Предсказание: 0.79999998
[1]Ошибка: 9.86049000000484e-09    Предсказание: 0.8000993000000001
[2]Ошибка: 3.999999995789153e-14    Предсказание: 0.7999998000000001



[0]Ошибка: 3.99920003999954e-08    Предсказание: 0.80019998
[1]Ошибка: 3.608404899998781e-07    Предсказание: 0.799399300000

In [11]:
weight = 0.5
goal_pred = 0.8
input = 2
alpha = 0.1
for iteration in range(20):
    pred = input * weight
    error = (pred - goal_pred) ** 2
    derivative = input * (pred - goal_pred)
    weight = weight - (alpha * derivative)
    print("Error:" + str(error) + " Prediction:" + str(pred))

Error:0.03999999999999998 Prediction:1.0
Error:0.0144 Prediction:0.92
Error:0.005183999999999993 Prediction:0.872
Error:0.0018662400000000014 Prediction:0.8432000000000001
Error:0.0006718464000000028 Prediction:0.8259200000000001
Error:0.00024186470400000033 Prediction:0.815552
Error:8.70712934399997e-05 Prediction:0.8093312
Error:3.134566563839939e-05 Prediction:0.80559872
Error:1.1284439629823931e-05 Prediction:0.803359232
Error:4.062398266736526e-06 Prediction:0.8020155392
Error:1.4624633760252567e-06 Prediction:0.8012093235200001
Error:5.264868153690924e-07 Prediction:0.8007255941120001
Error:1.8953525353291194e-07 Prediction:0.8004353564672001
Error:6.82326912718715e-08 Prediction:0.8002612138803201
Error:2.456376885786678e-08 Prediction:0.8001567283281921
Error:8.842956788836216e-09 Prediction:0.8000940369969153
Error:3.1834644439835434e-09 Prediction:0.8000564221981492
Error:1.1460471998340758e-09 Prediction:0.8000338533188895
Error:4.125769919393652e-10 Prediction:0.80002031199

In [15]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
weights = [0.1, 0.2, -0.1]

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred


toes = [8.5 , 9.5, 9.9, 9.0]
wlrec = [0.6, 0.8, 0.8, 0.9]
nfans = [1.2 , 1.3, 0.5, 1.0]
win_or_lose_binary = [1, 1, 0, 1]

true = win_or_lose_binary[0]
input = [toes[0],wlrec[0],nfans[0]]

pred = neural_network(input,weights)
error = (pred - true) ** 2
delta = pred - true


In [16]:
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input, weights)
error = (pred - true) ** 2
delta = pred - true
weight_deltas = ele_mul(delta,input)
print(weight_deltas)

[-1.2749999999999992, -0.08999999999999994, -0.17999999999999988]


In [19]:
input = [toes[0],wlrec[0],nfans[0]]
pred = w_sum(input,weights)
error = (pred - true) ** 2
delta = pred - true
weight_deltas = ele_mul(delta,input)
alpha = 0.01
for i in range(len(weights)):
    weights[i] -= alpha * weight_deltas[i]
print("Weights:" + str(weights))
print("Weight Deltas:" + str(weight_deltas))

Weights:[0.11275, 0.20090000000000002, -0.09820000000000001]
Weight Deltas:[-1.2749999999999992, -0.08999999999999994, -0.17999999999999988]
